AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura EC2 basica para Tactical Support Cloud
Parameters:
  KeyName:
    Description: Nombre del par de claves EC2 para acceso SSH
    Type: AWS::EC2::KeyPair::KeyName
  AdminCidr:
    Description: Red publica autorizada para SSH en formato CIDR (ejemplo 203.0.113.10/32)
    Type: String
    AllowedPattern: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}/(?:[0-9]|[12][0-9]|3[0-2])$'
    ConstraintDescription: Debe ingresar una direccion IPv4 con prefijo CIDR.
  LatestAmiId:
    Description: AMI Amazon Linux 2023 por SSM Parameter
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
Resources:
  TacticalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite HTTP publico y SSH restringido manualmente
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AdminCidr
      Tags:
        - Key: Name
          Value: tactical-support-sg
  TacticalInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref TacticalSecurityGroup
      Tags:
        - Key: Name
          Value: tactical-support-cloud
Outputs:
  PublicIP:
    Description: IP publica de la instancia EC2
    Value: !GetAtt TacticalInstance.PublicIp
  WebURL:
    Description: URL de prueba
    Value: !Sub 'http://${TacticalInstance.PublicIp}'
